language: java
jdk: oraclejdk8
sudo: required
group: deprecated-2017Q2

services:
  - docker
cache:
  directories:
  - $HOME/.m2/repository
deploy:
  provider: script
  script: sh $TRAVIS_BUILD_DIR/.travis.deploy.sh
  skip_cleanup: true
  on:
    branch: master
